const culturalData = [
    {
        name: "תרבוטק+ ספריית אביטל",
        address: "יוספטל 98, בת ים",
        lat: 32.015439,
        lon: 34.760644,
        type: "ספריה",
        targetAudience: "גיל שלישי 60+",
        website: "https://www.bat-yam.muni.il/he/249/",
        activity: ["מופעים", "נותן שירותים", "ערבי תרבות", "סדנאות"],
        artField: ["בין/רב תחומי"]
    },
    {
        name: "תרבוטק+ ספריית אביטל",
        address: null,
        lat: 32.015439,
        lon: 34.760644,
        type: "אתר מורשת תרבותית",
        targetAudience: "קהל רחב, אחר",
        website: "https://www.facebook.com/tarbutek.batyam",
        activity: [],
        artField: ["אומנות המילה"]
    },
    {
        name: "תרבוטק+ ספריית אביטל",
        address: null,
        lat: 32.015439,
        lon: 34.760644,
        type: null,
        targetAudience: "קהל רחב, אחר",
        website: "https://www.coing.co/BatYam_Tarbutek",
        activity: [],
        artField: []
    },
    {
        name: "קונסרבטיון למוסיקה",
        address: "ליבורנו 24 בת ים",
        lat: 32.011559,
        lon: 34.759953,
        type: "מוסד תרבות (כללי)",
        targetAudience: "נוער 12-18",
        website: "",
        activity: ["חוגים", "מופעים"],
        artField: ["מוסיקה"]
    },
    {
        name: "היכל התרבות",
        address: "סמטת אופיר 3",
        lat: 32.020639,
        lon: 34.757244,
        type: "אולם מופעים",
        targetAudience: "",
        website: "",
        activity: ["מופעים"],
        artField: ["בין/רב תחומי"]
    },
    {
        name: "אודיטוריום בת ים",
        address: "הדדי",
        lat: 32.0167,
        lon: 34.75,
        type: "אולם מופעים",
        targetAudience: "קהל רחב",
        website: "",
        activity: ["מופעים"],
        artField: ["בין/רב תחומי"]
    },
    {
        name: "המכון לאמנות",
        address: "הגבול, שמחה הולצברג 18",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "נוער 12-18, young adults 18-30, קהל רחב",
        website: "",
        activity: ["סדנאות", "חוגים", "תערוכות"],
        artField: ["אמנות פלסטית"]
    },
    {
        name: "מוזיאון בן ארי - MOBY - מוזיאון בת ים",
        address: "סטרומה 6, בת ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוזיאון",
        targetAudience: "קהל רחב",
        website: "",
        activity: ["תערוכות"],
        artField: ["אמנות פלסטית"]
    },
    {
        name: "בית שלום אש - מוזאוני בת ים",
        address: "ארלוזרוב 50 , בת ים",
        lat: 32.0167,
        lon: 34.75,
        type: "אתר מורשת תרבותית",
        targetAudience: "קהל רחב",
        website: "",
        activity: ["תערוכות"],
        artField: ["אמנות פלסטית"]
    },
    {
        name: "בית ריבק - מוזיאוני בת ים",
        address: "שאול הדדי, 6",
        lat: 32.0167,
        lon: 34.75,
        type: "מוזיאון",
        targetAudience: "קהל רחב",
        website: "",
        activity: ["סדנאות"],
        artField: ["בין/רב תחומי"]
    },
    {
        name: "בית-צדיק",
        address: "שאול המלך 4 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, נוער 12-18, משפחות צעירות 30+",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "גאולים",
        address: "ניצנה 19 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, young adults 18-30, משפחות צעירות 30+",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "גורדון",
        address: "ביל\"ו 1 פינת הגבול בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, young adults 18-30, משפחות צעירות 30+",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "הבונים",
        address: "אורט ישראל 9 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, נוער 12-18, משפחות צעירות 30+",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "יגלום",
        address: "ליבורנו 17 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, נוער 12-18",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "כותר-פיס",
        address: "ז'בוטינסקי 3 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, young adults 18-30",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "כנרת",
        address: "כנרת 6 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "ילדים 5-12, נוער 12-18, משפחות צעירות 30+",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    },
    {
        name: "עופר",
        address: "הבנים 5 בת-ים",
        lat: 32.0167,
        lon: 34.75,
        type: "מוסד תרבות (כללי)",
        targetAudience: "",
        website: "",
        activity: ["חוגים"],
        artField: ["מרכזים קהילתיים (מתנ\"ס)"]
    }
];
